# properties
name: AntiPieRay-OG
version: '${version}'
main: net.trueog.antipierayog.AntiPieRayOG
description: Attempts to prevent the usage of the PieRay exploit to find bases.
api-version: '${apiVersion}'

# libraries
libraries:
  - net.orbyfied.j8:j8-util:0.2.2.1

# commands
commands:
  antipieray:
    description: AntiPieRay-OG main command